# Checks the PR itself for hygiene things.

name: PR Lint

on:
  pull_request:
    # Necessary to re-run if someone edits the PR without a new pushed commit.
    types: [opened, edited, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: mdn/translated-content

      - uses: actions/checkout@v2
        with:
          repository: mdn/content
          path: mdn/content
          # Yes, this means fetch EVERY COMMIT EVER.
          # It's probably not sustainable in the far future (e.g. past 2021)
          # but for now it's good enough. We'll need all the history
          # so we can figure out each document's last-modified date.
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "12"

      - name: Install all yarn packages
        run: |
          cd $GITHUB_WORKSPACE/mdn/content/
          cd pr-lint
          yarn --frozen-lockfile

      - name: Run checks
        run: |
          cd $GITHUB_WORKSPACE/mdn/content/
          cd pr-lint
          yarn run check
